export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST";
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS";
export const ALL_BLOG_FAILED = "ALL_BLOG_FAILED";

export const SINGLE_BLOG_POST_SUCCESS = "SINGLE_BLOG_POST_SUCCESS";
export const SINGLE_BLOG_POST_REQUEST = "SINGLE_BLOG_POST_REQUEST";
export const SINGLE_BLOG_POST_FAILED = "SINGLE_BLOG_POST_FAILED";

export const CREATE_BLOG_POST_SUCCESS = "CREATE_BLOG_POST_SUCCESS";
export const CREATE_BLOG_POST_REQUEST = "CREATE_BLOG_POST_REQUEST";
export const CREATE_BLOG_POST_FAILED = "CREATE_BLOG_POST_FAILED";
export const CREATE_BLOG_POST_RESET = "CREATE_BLOG_POST_RESET";


export const ALL_BLOG_CLEAR_ERROR = "ALL_BLOG_CLEAR_ERROR";
