export const BLOG_CATEGORY_SUCCESS="BLOG_CATEGORY_SUCCESS";
export const BLOG_CATEGORY_REQUEST="BLOG_CATEGORY_REQUEST";
export const BLOG_CATEGORY_FAILED="BLOG_CATEGORY_FAILED";
export const CATEGORY_CLEAR_ERROR="CATEGORY_CLEAR_ERROR";