export const ALL_BLOG_REQUEST="ALL_BLOG_REQUEST";
export const ALL_BLOG_SUCCESS="ALL_BLOG_SUCCESS";
export const ALL_BLOG_FAILED="ALL_BLOG_FAILED";
export const ALL_BLOG_CLEAR_ERROR="ALL_BLOG_CLEAR_ERROR";

export const SINGLE_BLOGPAGE_SUCCESS="SINGLE_BLOGPAGE_SUCCESS";
export const  SINGLE_BLOGPAGE_REQUEST="SINGLE_BLOGPAGE_REQUEST";
export const SINGLE_BLOGPAGE_FAILED="SINGLE_BLOGPAGE_FAILED";
export const SINGLE_BLOGPAGE_CLEAR_ERROR="SINGLE_BLOGPAGE_CLEAR_ERROR";